[tools]
act = "0.2.83"
actionlint = "1.7.9"
atuin = "18.8.0"
container-structure-test = "1.22.0"
direnv = "2.37.1"
go = "1.25.5"
golangci-lint = "2.6.2"
hadolint = "2.14.0"
helm = "4.0.1"
helm-docs = "1.14.2"
helmfile = "1.2.2"
k9s = "0.50.15"
node = { version = "25.2.1", os = ["macos"] }
poetry = "2.2.1"
python = "3.14.0"
skaffold = "2.17.0"
talhelper = "3.0.41"
talosctl = "1.11.5"
terraform = "1.14.1"
terraform-docs = "0.20.0"
terraformer = "0.8.30"
tflint = "0.60.0"
tfsec = "1.28.14"
trivy = "0.68.1"
yq = "4.49.2"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
