[tools]
act = "0.2.82"
actionlint = "1.7.8"
atuin = "18.8.0"
container-structure-test = "1.21.1"
direnv = "2.37.1"
go = "1.25.4"
golangci-lint = "2.6.2"
hadolint = "2.14.0"
helm = "4.0.0"
helm-docs = "1.14.2"
helmfile = "1.2.1"
k9s = "0.50.15"
node = { version = "25.2.0", os = ["macos"] }
poetry = "2.2.1"
python = "3.14.0"
skaffold = "2.16.1"
talhelper = "3.0.39"
talosctl = "1.11.5"
terraform = "1.13.5"
terraform-docs = "0.20.0"
terraformer = "0.8.30"
tflint = "0.59.1"
tfsec = "1.28.14"
trivy = "0.67.2"
yq = "4.48.2"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
