[tools]
act = "0.2.84"
actionlint = "1.7.10"
atuin = "18.8.0"
container-structure-test = "1.22.1"
direnv = "2.37.1"
go = "1.26.0"
golangci-lint = "2.9.0"
hadolint = "2.14.0"
helm = "4.1.1"
helm-docs = "1.14.2"
helmfile = "1.2.3"
k9s = "0.50.15"
kustomize = "5.8.1"
node = { version = "25.6.1", os = ["macos"] }
poetry = "2.3.2"
python = "3.14.3"
skaffold = "2.17.1"
talhelper = "3.1.4"
talosctl = "1.12.3"
terraform = "1.14.5"
terraform-docs = "0.21.0"
terraformer = "0.8.30"
tflint = "0.61.0"
tfmigrate = "0.4.4"
tfsec = "1.28.14"
trivy = "0.69.1"
yq = "4.52.2"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
